// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Blouds Dispensary",
  domain: "bloudsdispensary.ca",
  city: "Brampton",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-brampton",
  address: "117 Queen St W, Brampton, ON L6Y 1M3",
  streetAddress: "117 Queen St W",
  postalCode: "L6Y 1M3",
  phone: "(437) 425-0117",
  phoneIntl: "+14374250117",
  neighborhood: "Brampton",
  nearbyAreas: ["Brampton", "Downtown Brampton", "Queen Street", "Main Street", "Kennedy Road", "Bramalea", "Peel Region", "Brampton Transit"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.app.goo.gl/yVDY1PZ8qSwAjQ6s6",
  mapEmbedUrl: "https://maps.google.com/maps?q=Blouds%20Dispensary%20117%20Queen%20St%20W%2C%20Brampton%2C%20ON%20L6Y%201M3&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.6894",
  longitude: "-79.7516",
  hours: ["Open 24 Hours"],
  seoTitle: "Blouds Dispensary | Weed Dispensary in Brampton",
  metaDescription: "Blouds Dispensary is a local weed dispensary in Brampton offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Brampton", "Downtown Brampton", "Queen Street"],
  introVariant: "Blouds Dispensary is your welcoming neighborhood weed dispensary in Brampton, located at 117 Queen St W near Brampton. We carry a massive selection of weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and smoking accessories for adults 19+. Conveniently located near Downtown Brampton, our cannabis store and weed shop is designed to make finding the perfect strain easy and accessible.",
  neighborhoodDescription: "Located in the vibrant Brampton district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Ample parking spaces are available nearby in Downtown Brampton municipal parking lots",
  transitNote: "Accessible by local Brampton Transit routes serving Downtown Brampton and the Peel Region.",
  sectionTitle: "Serving Customers Near Brampton and Peel Region"
};
